import sapien.core.pysapien.renderer
import typing
import numpy
_Shape = typing.Tuple[int, ...]

__all__ = [
    "Context",
    "Material",
    "Mesh",
    "Model",
    "Node",
    "Shape",
    "Texture",
    "UICheckbox",
    "UIDisplayText",
    "UIInputFloat",
    "UIInputFloat2",
    "UIInputFloat3",
    "UIInputFloat4",
    "UIInputText",
    "UIRadioButtonGroup",
    "UISliderAngle",
    "UISliderFloat",
    "UIWidget",
    "UIWindow"
]


class Context():
    def __init__(self, max_num_materials: int = 5000, max_num_textures: int = 5000, default_mipmap_levels: int = 1) -> None: ...
    def create_material(self, arg0: numpy.ndarray[numpy.float32], arg1: float, arg2: float, arg3: float) -> Material: ...
    def create_model_from_file(self, filename: str) -> None: ...
    def create_texture_from_file(self, filename: str, mipmap_levels: int, filter: str = 'linear', address_mode: str = 'repeat') -> Texture: ...
    pass
class Material():
    pass
class Mesh():
    pass
class Model():
    pass
class Node():
    pass
class Shape():
    pass
class Texture():
    pass
class UIWidget():
    def remove(self) -> None: ...
    pass
class UIDisplayText(UIWidget):
    def Text(self, text: str) -> UIDisplayText: ...
    def __init__(self) -> None: ...
    pass
class UIInputFloat(UIWidget):
    def Label(self, label: str) -> UIInputFloat: ...
    def Value(self, value: float) -> UIInputFloat: ...
    def __init__(self) -> None: ...
    def get(self) -> float: ...
    pass
class UIInputFloat2(UIWidget):
    def Label(self, label: str) -> UIInputFloat2: ...
    def Value(self, value: numpy.ndarray[numpy.float32]) -> UIInputFloat: ...
    def __init__(self) -> None: ...
    def get(self) -> numpy.ndarray[numpy.float32]: ...
    pass
class UIInputFloat3(UIWidget):
    def Label(self, label: str) -> UIInputFloat3: ...
    def Value(self, value: numpy.ndarray[numpy.float32]) -> UIInputFloat: ...
    def __init__(self) -> None: ...
    def get(self) -> numpy.ndarray[numpy.float32]: ...
    pass
class UIInputFloat4(UIWidget):
    def Label(self, label: str) -> UIInputFloat4: ...
    def Value(self, value: numpy.ndarray[numpy.float32]) -> UIInputFloat: ...
    def __init__(self) -> None: ...
    def get(self) -> numpy.ndarray[numpy.float32]: ...
    pass
class UIInputText(UIWidget):
    def Label(self, label: str) -> UIInputText: ...
    def Size(self, size: int) -> UIInputText: ...
    def __init__(self) -> None: ...
    pass
class UIRadioButtonGroup(UIWidget):
    def Callback(self, func: typing.Callable[[UIRadioButtonGroup], None]) -> UIRadioButtonGroup: ...
    def Labels(self, labels: typing.List[str]) -> UIRadioButtonGroup: ...
    def __init__(self) -> None: ...
    @property
    def index(self) -> int:
        """
        :type: int
        """
    @property
    def value(self) -> str:
        """
        :type: str
        """
    pass
class UISliderAngle(UIWidget):
    def Callback(self, func: typing.Callable[[UISliderAngle], None]) -> UISliderAngle: ...
    def Label(self, label: str) -> UISliderAngle: ...
    def Max(self, max: float) -> UISliderAngle: ...
    def Min(self, min: float) -> UISliderAngle: ...
    def Value(self, value: float) -> UISliderAngle: ...
    def __init__(self) -> None: ...
    def get(self) -> float: ...
    pass
class UISliderFloat(UIWidget):
    def Callback(self, func: typing.Callable[[UISliderFloat], None]) -> UISliderFloat: ...
    def Label(self, label: str) -> UISliderFloat: ...
    def Max(self, max: float) -> UISliderFloat: ...
    def Min(self, min: float) -> UISliderFloat: ...
    def Value(self, value: float) -> UISliderFloat: ...
    def __init__(self) -> None: ...
    def get(self) -> float: ...
    pass
class UICheckbox(UIWidget):
    def Callback(self, func: typing.Callable[[UICheckbox], None]) -> UICheckbox: ...
    def Checked(self, checked: bool) -> UICheckbox: ...
    def Label(self, label: str) -> UICheckbox: ...
    def __init__(self) -> None: ...
    @property
    def checked(self) -> bool:
        """
        :type: bool
        """
    pass
class UIWindow(UIWidget):
    def Label(self, Label: str) -> UIWindow: ...
    def Pos(self, x: float, y: float) -> UIWindow: ...
    def Size(self, x: float, y: float) -> UIWindow: ...
    def __init__(self) -> None: ...
    def append(self, *args) -> UIWindow: ...
    pass
