#!/usr/bin/env python3

import subprocess
import argparse
import sys


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("command", type=str)

    args, rest = parser.parse_known_args()
    if args.command == "install":
        package = rest[0]
        args = [
            sys.executable,
            "-m",
            "pip",
            "install",
            "--user",
            f"git+https://github.com/sapien-sim/{package}",
        ]

        subprocess.run(args)

    elif args.command == "uninstall":
        package = rest[0]
        args = [
            sys.executable,
            "-m",
            "pip",
            "uninstall",
            f"sapien_{package}",
        ]

        subprocess.run(args)
