name: TestWindowsBuild

on:
  push:
    branches: [main, dev, test-windows]

jobs:
  # build-linux:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   container:
  #     image: fxiangucsd/sapien-build-env:3.3
  #     env:
  #       CMAKE_BUILD_PARALLEL_LEVEL: 2
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: "true"
  #     - name: Set up cmake cache
  #       uses: actions/cache@v3
  #       with:
  #         path: docker_sapien_build/_sapien_deps
  #         key: ${{ runner.os }}.${{ hashFiles('**/*.cmake', '**/CMakeLists.txt') }}
  #     - name: Build wheels
  #       run: "git config --global --add safe.directory '*' && ./build.sh"
  #     - name: Upload wheels
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: wheels
  #         path: ./wheelhouse/*.whl

  build-windows:
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: setup CUDA
        shell: bash
        run: |
          C:/msys64/usr/bin/wget.exe https://developer.download.nvidia.com/compute/cuda/11.8.0/network_installers/cuda_11.8.0_windows_network.exe
          ./cuda_11.8.0_windows_network.exe -s cuda_profiler_api_11.8 cudart_11.8 cuobjdump_11.8 cupti_11.8 cuxxfilt_11.8 demo_suite_11.8 documentation_11.8 memcheck_11.8 nvcc_11.8 nvdisasm_11.8 nvml_dev_11.8 nvprof_11.8 nvprune_11.8 nvrtc_dev_11.8 nvtx_11.8 visual_profiler_11.8 sanitizer_11.8 thrust_11.8 cublas_dev_11.8 cufft_dev_11.8 curand_dev_11.8 cusolver_dev_11.8 cusparse_dev_11.8 npp_dev_11.8 nvjpeg_dev_11.8 nsight_compute_11.8 nsight_nvtx_11.8 nsight_systems_11.8 nsight_vse_11.8 visual_studio_integration_11.8 occupancy_calculator_11.8
      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.11
      - name: Build wheels
        env:
          CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
        run: |
          ls "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8"
          python -m pip install setuptools wheel
          python --version
          python setup.py --sapien-only --build-dir=sapien_build
          python setup.py --pybind-only --build-dir=sapien_build
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: windows-wheels
          path: ./dist/*.whl


      # - name: Update Nightly Release
      #   uses: andelf/nightly-release@main
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: nightly
      #     name: 'Nightly Release'
      #     prerelease: true
      #     body: 'SAPIEN development nightly release. This release is mainly for internal testing. Stable releases are published to pypi https://pypi.org/project/sapien/'
      #     files: |
      #       ./wheelhouse/*.whl
